version: '3'
services:
  my_item_repository:
    image: jakobj13/hgop:game_${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_postgres_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'my_postgres_container'
      POSTGRES_DB: 'my_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'
  my_postgres_container:
    image: postgres
    environment:
      POSTGRES_DB: 'my_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'
  my_ui_container:
    image: jakobj13/hgop:ui_${GIT_COMMIT}
    ports: 
      - '4000:4000'
    environment:
      PORT: 4000
      #API_URL: 'http://localhost' #${API_URL}
      #API_PORT_URL: 3000
    depends_on: 
      - my_item_repository
